version: "3"

services:
    traefik:
        image: traefik:v2.10
        container_name: traefik
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--accesslog=true"
            - "--accesslog.filepath=/var/log/access.log"
        ports:
            - "8083:80" # The HTTP port
            - "8081:8080" # The Web UI (enabled by --api.insecure=true)
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik/logs:/var/log

    app:
        build:
            context: .
            dockerfile: Dockerfile
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.app.entrypoints=web"  # Match the entry point defined in Traefik
            - "traefik.http.routers.app.rule=Host(`newblog.james-nock.co.uk`)"  # Define a routing rule
            - "traefik.http.services.app.loadbalancer.server.port=8000"
        volumes:
            - app_data:/var/www
            - ./storage/app/static:/var/www/public
        depends_on:
            - nginx

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./storage/app/static:/usr/share/nginx/html
        depends_on:
            - app

volumes:
    app_data:
