name: Build & Deploy
on:
  push:
    branches:
      - lightsail
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz --delete . ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:newblog/${GITHUB_SHA}

      - name: Deploy to Lightsail
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
          GITHUB_SHA: ${{ secrets.GITHUB_SHA }}
        run: |
          # Ensure SSH is available
          ssh -o StrictHostKeyChecking=no $LIGHTSAIL_USER@$LIGHTSAIL_HOST 'echo "SSH connection established"'

          # Copy ENV (composer)
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "cd ~/blog && cp ~/envs/blog/$GITHUB_SHA/.env .env"


          # Install dependencies (composer)
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "cd ~/newblog/$GITHUB_SHA && composer install"

          # Install dependencies (npm)
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "cd ~/newblog/$GITHUB_SHA && nvm use || nvm install $(cat ~/newblog/$GITHUB_SHA/.nvmrc) && npm install && npm run build"

          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "cd ~/newblog && rm ~/newblog/current 2> /dev/null && ln -s ~/newblog/$GITHUB_SHA ~/newblog/current && cd ~/newblog && ls -dt | tail -n +3 | xargs rm -rf"

      - name: Notify deployment success
        run: echo "Deployment to Lightsail successful!"
