name: Build & Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz --delete . ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:blog/${GITHUB_SHA}

      - name: Deploy to Lightsail
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
          GITHUB_SHA: ${{ secrets.GITHUB_SHA }}
          WORKDIR: "blog"
        run: |
          # Ensure SSH is available
          #ssh -vvv -o StrictHostKeyChecking=no $LIGHTSAIL_USER@$LIGHTSAIL_HOST

          # Copy ENV
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "cp ~/envs/$WORKDIR/.env ~/$WORKDIR/$GITHUB_SHA/.env"

          # Install dependencies (composer)
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "cd ~/$WORKDIR/$GITHUB_SHA && composer install"

#          # Install dependencies (npm)
#          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "cd ~/$WORKDIR/$GITHUB_SHA && nvm use || nvm install $(cat ~/$WORKDIR/$GITHUB_SHA/.nvmrc) && npm install && npm run build"

          # Change symlink and delete old version
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "cd ~/$WORKDIR && rm ~/$WORKDIR/current 2> /dev/null && ln -s ~/$WORKDIR/$GITHUB_SHA ~/$WORKDIR/current"

          # Fix permissions
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "cd ~/$WORKDIR/$GITHUB_SHA && chmod -R 755 storage/app/static"

          # Change symlink and delete old versions
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "cd ~/$WORKDIR && rm ~/$WORKDIR/current 2> /dev/null && ln -s ~/$WORKDIR/$GITHUB_SHA ~/$WORKDIR/current && cd ~/$WORKDIR && ls -dt | tail -n +3 | xargs rm -rf"

      - name: Notify deployment success
        run: echo "Deployment to Lightsail successful!"
