name: Build & Deploy
on:
  push:
    branches:
      - lightsail
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Deploy to Lightsail
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
        run: |
          # Ensure SSH is available
          ssh -o StrictHostKeyChecking=no $LIGHTSAIL_USER@$LIGHTSAIL_HOST 'echo "SSH connection established"'

          # Navigate to the web application directory (adjust as needed)
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST 'cd ~/newblog/${GITHUB_SHA} && git pull origin lightsail'

          # Install dependencies (adjust as needed)
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST 'cd /path/to/app && npm install && cp ~/envs/newblog/.env . && composer install && nvm use || nvm install $(cat .nvmrc) && npm install && npm run build'

          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST 'cd ~/newblog && rm ~/newblog/current 2> /dev/null && ln -s ~/newblog/${GITHUB_SHA} ~/newblog/current && cd ~/newblog && ls -dt */ | tail -n +3 | xargs rm -rf'

      - name: Notify deployment success
        run: echo "Deployment to Lightsail successful!"
