name: Build & Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "unnecessary"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz --delete . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:newblog/${GITHUB_SHA}

      - name: Build site
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${GITHUB_SHA}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: GITHUB_SHA
          script: |
            cd ~/newblog/${GITHUB_SHA}
            cp ~/envs/newblog/.env .
            composer install
            nvm use || nvm install $(cat .nvmrc)
            npm install
            npm run build
            cd ~/newblog
            rm ~/newblog/current 2> /dev/null
            ln -s ~/newblog/${GITHUB_SHA} ~/newblog/current
            cd ~/newblog
            ls -dt */ | tail -n +3 | xargs rm -rf
